version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 904450061599.dkr.ecr.us-east-1.amazonaws.com
      - echo "Instalando dependencias para validar"
      - pip install -r blacklist/src/requirements.txt
      - pip install coverage
  build:
    commands:
      - echo "Seteando PYTHONPATH"
      - export PYTHONPATH="${PYTHONPATH}:$(pwd)/blacklist/src"
      
      - echo "Ejecutando pruebas con unittest"
      - coverage run -m unittest discover -s blacklist/src/tests
      - coverage report --fail-under=80
      
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t python_app .
      - docker tag python_app:latest 904450061599.dkr.ecr.us-east-1.amazonaws.com/python_app:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 904450061599.dkr.ecr.us-east-1.amazonaws.com/python_app:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"904450061599.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"904450061599.dkr.ecr.us-east-1.amazonaws.com/python_app:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json